

/* AUTH ACTIONS */
export const AUTH_START       = "AUTH_START";
export const AUTH_SUCCESS     = "AUTH_SUCEESS";
export const AUTH_FAIL_LOGIN  = 'AUTH_FAIL_LOGIN';
export const AUTH_FAIL_SIGNUP = 'AUTH_FAIL_SIGNUP';
export const AUTH_LOGOUT      = "AUTH_LOGOUT";
export const CLEAR_AUTH_ERRORS = "CLEAR_AUTH_ERRORS";


/* ADMIN MANAGE ITEMS */
export const ADMIN_DELETE_ITEM = "ADMIN_DELETE_ITEM";

/* GET DATATBASE ITEMS */
export const START_FETCHING = "START_FETCHING";
export const ALL_CATEGORY_ITEMS = "ALL_CATEGORY_ITEMS";

/* HANDLE CART ITEMS */
export const USER_CART_ITEMS  = "USER_CART_ITEMS";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";

export const CLEAR_STATE = "CLEAR_STATE";
export const CLREAR_CART = "CLREAR_CART";
export const CLREAR_TOASTER = "CLREAR_TOASTER";
export const ADD_CART_ITEM_TO_TOASTER = "ADD_CART_ITEM_TO_TOASTER";

export const CUSTOM_CATEGORY = "CUSTOM_CATEGORY";